# -*- coding: utf-8 -*-
"""Yolov8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_fvENPrZrgDS8bwbp5L-kWkOgbI-0R1
"""

!nvidia-smi

!pip install ultralytics

from ultralytics import YOLO

!yolo task=detect mode=predict model=yolov8l.pt conf=0.25 source="https://ultralytics.com/images/bus.jpg"

"""Custom Data Training"""

!yolo mode=train task=detect model=yolov8l.pt data=../content/drive/MyDrive/Dataset/SafetyProject/data.yaml epochs=50 imgsz=640

